export const GET_PRODUCT_TOP_REQUEST = 'GET_PRODUCT_TOP_REQUEST'
export const GET_PRODUCT_TOP_SUCCESS = ' GET_PRODUCT_TOP_SUCCESS'
export const GET_PRODUCT_TOP_FAILED = ' GET_PRODUCT_TOP_FAILED'

export const GET_PRODUCT_TOP_SEARCH_REQUEST = 'GET_PRODUCT_TOP_SEARCH_REQUEST'
export const GET_PRODUCT_TOP_SEARCH_SUCCESS = 'GET_PRODUCT_TOP_SEARCH_SUCCESS'
export const GET_PRODUCT_TOP_SEARCH_FAILED = 'GET_PRODUCT_TOP_SEARCH_FAILED'

export const GET_PRODUCT_SUGGEST_REQUEST = 'GET_PRODUCT_SUGGEST_REQUEST'
export const GET_PRODUCT_SUGGEST_SUCCESS = 'GET_PRODUCT_SUGGEST_SUCCESS'
export const GET_PRODUCT_SUGGEST_FAILED = 'GET_PRODUCT_SUGGEST_FAILED'

export const GET_LIST_PRODUCT_REQUEST = 'GET_LIST_PRODUCT_REQUEST'
export const GET_LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS'
export const GET_LIST_PRODUCT_FAILED = 'GET_LIST_PRODUCT_FAILED'
