export const GET_DETAIL_PRODUCT_REQUEST = 'GET_DETAIL_PRODUCT_REQUEST'
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS'
export const GET_DETAIL_PRODUCT_FAILED = 'GET_DETAIL_PRODUCT_FAILED'

export const GET_COMMENT_REQUEST = 'GET_COMMENT_REQUEST'
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS'
export const GET_COMMENT_FAILED = 'GET_COMMENT_FAILED'

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST'
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'
export const POST_COMMENT_FAILED = 'POST_COMMENT_FAILED'

export const LIKE_PRODUCT_REQUEST = 'LIKE_PRODUCT_REQUEST'
export const LIKE_PRODUCT_SUCCESS = 'LIKE_PRODUCT_SUCCESS'
export const LIKE_PRODUCT_FAILED = 'LIKE_PRODUCT_FAILED'
