export const FETCH_SAME_PRODUCT_REQUEST = 'FETCH_SAME_PRODUCT_REQUEST'
export const FETCH_SAME_PRODUCT_SUCCESS = 'FETCH_SAME_PRODUCT_SUCCESS'
export const FETCH_SAME_PRODUCT_FAILED = 'FETCH_SAME_PRODUCT_FAILED'
