export const FETCH_SEEN_RECENT_REQUEST = 'FETCH_SEEN_RECENT_REQUEST'
export const FETCH_SEEN_RECENT_SUCCESS = 'FETCH_SEEN_RECENT_SUCCESS'
export const FETCH_SEEN_RECENT_FAILED = 'FETCH_SEEN_RECENT_FAILED'
